Добавлены контроллеры каналов и групп
d1den/DataManagementServer pull request #20
Opened 2022-11-27 15:26 UTC by Alexey111231

2022-11-27 16:46 UTC, d1den commented on Src/DataManagementServer/Pagination/Pages/Page.cs
> +        public int TotalPageCount { get { return (int) Math.Ceiling(TotalElementsCount / ((double) PageSize)); } }
Если в свойстве реализуем только get, то более читаемо его реализовать через стрелочную функцию, например
public int TotalPageCount => (int)Math.Ceiling(TotalElementsCount / ((double) PageSize));

2022-11-27 16:47 UTC, d1den commented on Src/DataManagementServer/Pagination/Pages/Page.cs
> +                throw new ArgumentException(ErrorMessages.IncorrectPageNumber);
В таком случае лучше использовать ArgumentOutOfRangeException

2022-11-27 16:52 UTC, d1den commented on Src/DataManagementServer/Pagination/Pages/Page.cs
> +        public Page(IList<T> values, int pageSize, int pageNumber, int totalElementsCount)
Может быть передавать в объект пейджинга все значения, а уже в объекте определять общее число элементов, делать take и skip?
И я бы перенёс эту логику в sdk, так как может понадобиться пейджинг в контроллерах плагинов

2022-11-27 16:56 UTC, d1den commented on Src/DataManagementServer/DataManagementServer.Core/Services/Concrete/OrganizationService.cs
> +            if (model.GroupId != null && Guid.Empty.Equals(model.GroupId)) { (this as IGroupService).ExistOrTrown(model.GroupId ?? Guid.Empty); }
Тут ты два раза проверяешь model.GroupId на нулл (в условии и в вызове метода)

2022-11-27 17:03 UTC, d1den commented on Src/DataManagementServer/DataManagementServer.Core/Services/Concrete/OrganizationService.cs
> +        void IGroupService.ExistOrTrown(Guid groupId)
В моей идеи групп и каналов есть корневая группа, которая обозначается просто пустым guid. Возможно, стоило в каналах и группах сделать id родительской группы Guid? и тогда корневую задавать null, но сделать в итоге как есть и корневая - это Guid.Empty. Для удобства сделал константу в модели группы - RootId.
В общем, если id = GroupModel.RootGroupId (или Guid.Empty), то считаем что ок, это root и не ищем её в списке реальных групп. В других случаях да, проверяем

2022-11-27 17:04 UTC, d1den commented on Src/DataManagementServer/DataManagementServer.Core/Services/Concrete/OrganizationService.cs
> +            if (model.ParentId != null && Guid.Empty.Equals(model.ParentId)) { (this as IGroupService).ExistOrTrown(model.ParentId ?? Guid.Empty); }
Тут ты два раза проверяешь model.GroupId на нулл (в условии и в вызове метода)

2022-11-27 17:09 UTC, d1den commented on Src/DataManagementServer/DataManagementServer.AppServer/Utils/NotEmpty.cs
> +    public class NotEmpty : ValidationAttribute
Атрибуты принято в .net называть с суффиксом Attribute. При использовании его можно отбросить (как обычно и делается). Но в нейминге лучше указать

2022-11-27 17:12 UTC, d1den commented on Src/DataManagementServer/DataManagementServer.AppServer/Utils/NotEmpty.cs
> +                _ => true,
И если значение не guid, а применяем его только для Guid, то лучше выкидывать false

2022-11-28 06:22 UTC, d1den commented on Src/DataManagementServer/DataManagementServer.AppServer/Controllers/ChannelController.cs
> +
Есть несколько предложений по организации Web-api:
1) Уменьшить количество методов за счёт json модели в body, у которой часть параметров не обязательная.
Например, в данном случае, можно сделать CreateChannel([FromBody] ChannelModel model) и CreateDefaultChannel([FromBody] Guid? groupId), где id группы - необязательный параметр, если его нет, то создаём дефолтный канал, если есть - с привязкой к группе

2022-11-28 06:29 UTC, d1den commented on Src/DataManagementServer/DataManagementServer.AppServer/Controllers/ChannelController.cs
>          }
Аналогично комменту выше, тут можно было бы использовать оидн метод GetChannel, где json в body:
{ Guid channelId (обязательный),
IList<string> fields - необязательный }
Ну и тогда также в зависимости от необязательной части модели небольшое ветвление в логике

По поводу методов Rest и body - я вот сейчас осознал, что в параметрах uri там много данных может быть необходимо поместить - список полей, дальше ещё модель пагинации добавляется. С этим намного удобнее было бы работать через модель в body (с точки зрения фронта тоже проще json отправить в body). Предлагаю сделать некрасиво, зато удобно - реализовать все методы как POST. Get оставить для методов, которые файл будут возвращать или что-то такое

2022-11-28 06:32 UTC, d1den commented on Src/DataManagementServer/DataManagementServer.AppServer/Controllers/ChannelController.cs
> +        }
Ну если делать по аналогии выше, то тут можно один метод сделать

2022-11-28 06:33 UTC, d1den commented on Src/DataManagementServer/DataManagementServer.AppServer/Controllers/GroupController.cs
> +    public class GroupController : CommonController
Ну тут те же мысли, что и выше в ChannelController

2022-11-28 06:35 UTC, d1den requested changes
Я оставил пару комментов, часть из них больше по стилю шарпа и оформлению, а часть-вопросы к обсуждению логики

2022-11-28 19:23 UTC, Alexey111231 commented on Src/DataManagementServer/DataManagementServer.Core/Services/Concrete/OrganizationService.cs
> +            if (model.GroupId != null && Guid.Empty.Equals(model.GroupId)) { (this as IGroupService).ExistOrTrown(model.GroupId ?? Guid.Empty); }
дыа, потому что мне надо преобразовать нуллейбл тип в  обычный перед передачей в метод, но при этом я знаю, что он уже не нулл

2022-11-28 19:23 UTC, Alexey111231 commented on Src/DataManagementServer/DataManagementServer.Core/Services/Concrete/OrganizationService.cs
> +            if (model.GroupId != null && Guid.Empty.Equals(model.GroupId)) { (this as IGroupService).ExistOrTrown(model.GroupId ?? Guid.Empty); }
может подсказать как норм преобразовывать

2022-11-28 19:23 UTC, Alexey111231 commented on Src/DataManagementServer/DataManagementServer.Core/Services/Concrete/OrganizationService.cs
> +            if (model.GroupId != null && Guid.Empty.Equals(model.GroupId)) { (this as IGroupService).ExistOrTrown(model.GroupId ?? Guid.Empty); }
гугл выдает такой ответ

2022-11-28 20:09 UTC, Alexey111231 commented on Src/DataManagementServer/Pagination/Pages/Page.cs
> +        public int TotalPageCount { get { return (int) Math.Ceiling(TotalElementsCount / ((double) PageSize)); } }
Оке завтра поправлю

2022-11-28 20:09 UTC, Alexey111231 commented on Src/DataManagementServer/Pagination/Pages/Page.cs
> +                throw new ArgumentException(ErrorMessages.IncorrectPageNumber);
оке завтра поправлю

2022-11-28 20:10 UTC, Alexey111231 commented on Src/DataManagementServer/Pagination/Pages/Page.cs
> +        public Page(IList<T> values, int pageSize, int pageNumber, int totalElementsCount)
не, так делать не над, данные могут доставаться из разных мест и из бд например или файла доставать все это плохой варианет

2022-11-28 20:10 UTC, Alexey111231 commented on Src/DataManagementServer/Pagination/Pages/Page.cs
> +        public Page(IList<T> values, int pageSize, int pageNumber, int totalElementsCount)
позже сделаем правильный пейджинг

2022-11-28 20:10 UTC, Alexey111231 commented on Src/DataManagementServer/Pagination/Pages/Page.cs
> +        public Page(IList<T> values, int pageSize, int pageNumber, int totalElementsCount)
когда до сохранения дойдем

2022-11-28 20:10 UTC, Alexey111231 commented on Src/DataManagementServer/DataManagementServer.Core/Services/Concrete/OrganizationService.cs
> +            if (model.GroupId != null && Guid.Empty.Equals(model.GroupId)) { (this as IGroupService).ExistOrTrown(model.GroupId ?? Guid.Empty); }
оке завтра поправлю

2022-11-28 20:11 UTC, Alexey111231 commented on Src/DataManagementServer/DataManagementServer.Core/Services/Concrete/OrganizationService.cs
> +            if (model.ParentId != null && Guid.Empty.Equals(model.ParentId)) { (this as IGroupService).ExistOrTrown(model.ParentId ?? Guid.Empty); }
оке завтра поправлю

2022-11-28 20:11 UTC, Alexey111231 commented on Src/DataManagementServer/DataManagementServer.AppServer/Utils/NotEmpty.cs
> +    public class NotEmpty : ValidationAttribute
ок. возможно просто его уберу. когда переделаем на пустой гуид, а так завтра переименую

2022-11-28 20:12 UTC, Alexey111231 commented on Src/DataManagementServer/DataManagementServer.AppServer/Utils/NotEmpty.cs
> +                _ => true,
думаю да

2022-11-28 20:13 UTC, Alexey111231 commented on Src/DataManagementServer/DataManagementServer.AppServer/Controllers/ChannelController.cs
> +
не это фигня, особо выигрыша не будет, ток ифы лишнее будем смотреть, думаю лучше пусть методов будет для каждого запроса

2022-11-28 20:14 UTC, Alexey111231 commented on Src/DataManagementServer/DataManagementServer.AppServer/Controllers/ChannelController.cs
>          }
Да ничего неудобного быть не должно, список параметров скорее всего мапов передается на фронте

2022-11-28 20:14 UTC, Alexey111231 commented on Src/DataManagementServer/DataManagementServer.AppServer/Controllers/ChannelController.cs
> +        }
как и выше

2022-11-28 20:14 UTC, Alexey111231 commented on Src/DataManagementServer/DataManagementServer.AppServer/Controllers/GroupController.cs
> +    public class GroupController : CommonController
как и выше

2022-11-28 20:16 UTC, Alexey111231 commented on Src/DataManagementServer/DataManagementServer.AppServer/Controllers/ChannelController.cs
>          }
в современном js объект можно в мапу превратить

2022-11-28 20:18 UTC, Alexey111231 commented on Src/DataManagementServer/Pagination/Pages/Page.cs
> +        public Page(IList<T> values, int pageSize, int pageNumber, int totalElementsCount)
просто типо в страницу изначально должны извлекаться, только нужные данные, иначе это может быть большая копия данных, но конкретно в нашем приложении это врятли конечно, но все же страница не должно из всех данных что-то собирать, она должна кем-то собираться, тем же пейдж фактори или еще чем нить

2022-11-28 20:19 UTC, Alexey111231 commented on Src/DataManagementServer/DataManagementServer.AppServer/Utils/NotEmpty.cs
> +                _ => true,
завтра поправлю

2022-11-28 20:19 UTC, Alexey111231 commented on Src/DataManagementServer/DataManagementServer.AppServer/Controllers/ChannelController.cs
> +
типо разницы между веб апи с большим количеством параметров и веб апи с большим количестом методов практически нет

2022-11-28 20:20 UTC, Alexey111231 commented on Src/DataManagementServer/DataManagementServer.AppServer/Controllers/ChannelController.cs
>          }
вот, так что проблем с фронтом быть не должно вообще и считаю это удобным методом работы с апи

2022-11-29 05:44 UTC, d1den commented on Src/DataManagementServer/Pagination/Pages/Page.cs
> +        public Page(IList<T> values, int pageSize, int pageNumber, int totalElementsCount)
Понял. Страница чисто как модель выступает, тогда да, нормас

2022-11-29 05:45 UTC, d1den commented on Src/DataManagementServer/DataManagementServer.Core/Services/Concrete/OrganizationService.cs
> +        void IGroupService.ExistOrTrown(Guid groupId)
Можно и так сделать, да

2022-11-29 05:46 UTC, d1den commented on Src/DataManagementServer/DataManagementServer.AppServer/Controllers/ChannelController.cs
> +
Хорошо, давай так

2022-11-29 05:48 UTC, d1den commented on Src/DataManagementServer/DataManagementServer.AppServer/Controllers/ChannelController.cs
>          }
Ну ладно, разберемся с этим по ходу дела, пока окей, оставим как есть

2022-11-29 05:48 UTC, d1den commented on Src/DataManagementServer/DataManagementServer.AppServer/Controllers/GroupController.cs
> +    public class GroupController : CommonController
Ок

2022-11-29 05:48 UTC, d1den commented on Src/DataManagementServer/DataManagementServer.AppServer/Controllers/ChannelController.cs
> +        }
Ок

2022-11-29 08:49 UTC, d1den reviewed
Всё нормас, да)

2022-11-29 18:25 UTC, d1den approved these changes

2022-11-30 17:44 UTC, merged